version: '3'
services:
  # Databases
  db-relational:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: its
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db-its

  db-document:
    image: mongo:4
    ports:
      - '27017:27017'

  # Services
  broker:
    image: rabbitmq:3.9.13-alpine
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15672:15672'
      - '15692:15692'
      - '25672:25672'

  its-gateway:
    build:
      context: ./its__gateway/
      dockerfile: ./dev.Dockerfile
    ports:
      - '10000:80'
